In [2]:
import numpy as np

In [44]:
ground_truth = np.array([[0,0,0],[0,0,0],[0,0,0],[0,0,0]])
target_index = np.array([[1],[0],[2],[0]])

In [45]:
for i in range(len(ground_truth)):
    ground_truth[i, target_index[i]] = 1
ground_truth

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [46]:
np.take_along_axis(ground_truth, target_index, axis=-1)

array([[1],
       [1],
       [1],
       [1]])

In [47]:
target_index.reshape(len(target_index))

array([1, 0, 2, 0])

In [49]:
np.sum(1, axis=-1)


1

In [68]:
np.concatenate((ground_truth, np.ones((ground_truth.shape[0], 1))), axis=-1)

array([[0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 1., 1.],
       [1., 0., 0., 1.]])

In [61]:
np.concatenate(np.array([[0,1,2]]), np.array([[3,4,5]]))

TypeError: only integer scalar arrays can be converted to a scalar index

In [51]:
ground_truth

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [69]:
1>None

TypeError: '>' not supported between instances of 'int' and 'NoneType'

In [26]:
X = np.array([[1,2,3], [4,5,6], [7,8,9]])
dprediction = np.array([[1,0], [0,1], [1,0]])
# dW = np.sum(np.expand_dims(X, -1) * np.expand_dims(dprediction, -2), 0)
dW = np.einsum('ij,ik->jk', X, dprediction)
dW

array([[ 8,  4],
       [10,  5],
       [12,  6]])

In [5]:
dW

array([[1],
       [2],
       [3]])

In [22]:
from linear_classifer import *

X = np.array([[0,1,0], [1,0,1], [0,1,0], [0,0,1]])
W = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])

clf_output = X @ W
probs = softmax(clf_output)
y_pred = np.argmax(probs, axis=-1)

y_pred


array([1, 0, 1, 2], dtype=int64)

In [30]:
a = 1
a += 2+3
a

6

In [9]:
from collections import OrderedDict

class F:
    def __init__(self, x):
        self.x = x

class U:
    def __init__(self):
        self.Fs = {"1":F(1),
              "2":F(2)}

u = U();
for k, f in reversed(u.Fs.items()):
    f.x += 1

print([f.x for k, f in u.Fs.items()])

[2, 3]


In [10]:
for k, f in enumerate(reversed(u.Fs.values())):
    print(k)
    f.x += k

print([f.x for k, f in u.Fs.items()])

0
1
[3, 3]


In [75]:
import numpy as np
t_i = [[1], [2], [3]]
t_i = np.array(t_i, ndmin=2)
t_i = t_i.reshape(t_i.shape[0], 1)

# t_i.reshape(len(t_i), None)

In [76]:
t_i

array([[1],
       [2],
       [3]])